services:
  backend:
    image: shaun1092/venturenest-backend
    container_name: backend
    ports:
      - "4000:4000"
    env_file:
      - ./Backend/.env
    restart: always

  frontend:
    image: shaun1092/venturenest-frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
