export const SECTOR = [
  "AI/ML",
  "FinTech",
  "HealthTech",
  "EdTech",
  "AgriTech",
  "E-commerce",
  "SaaS",
  "BlockChain/Crypto",
  "GreenTech",
  "Real Estate/PropTech",
  "FoodTech",
  "Gaming",
  "Social Media",
  "Travel & Hospitality",
  "Logistic & SupplyChain",
  "CyberSecurity",
  "IoT/Hardware",
  "AR/VR",
  "Services",
] as const;
