export const FRONTEND_ROUTES = {
  LANDING: "/",

  USER: {
    SIGNUP: "/signup",
    LOGIN: "/login",
    FORGOT_PASSWORD: "/forgot-password",
    HOME: "/home",
    MYNETWORK: "/mynetwork",
    PROFILE: "/profile",
    NOTIFICATIONS: "/notifications",
    PROJECT: "/projects",
    PLANS: "/plans",
    PAYMENT_SUCCESS: "/payment-success",
    COMMON_PROFILE: "/profile/:id",
    SESSIONS: "/sessions",
    OFFERS: "/offers",
  },

  INVESTOR: {
    SIGNUP: "/signup",
    LOGIN: "/login",
    FORGOT_PASSWORD: "/forgot-password",
    PROFILE_COMPLETION: "/profile-completion",
    INTERESTED_TOPICS: "/interested-topics",
    HOME: "/home",
    MYNETWORK: "/mynetwork",
    PROFILE: "/profile",
    NOTIFICATIONS: "/notifications",
    PROJECT: "/projects",
    PLANS: "/plans",
    OFFERS: "/offers",
    PAYMENT_SUCCESS: "/payment-success",
    BOOK_SESSION: "/schedule-session",
    SESSIONS: "/sessions",
    SEND_OFFER: "/send-offer",
  },

  ADMIN: {
    LOGIN: "/login",
    DASHBOARD: "/dashboard",
    USERS: "/users",
    INVESTORS: "/investors",
    VERIFICATIONS: "/verifications",
    PROJECTS: "/projects",
    REPORTS: "/reports",
    SUBCRIPTION: "/subscriptions",
  },
};
