export enum DealStatus {
  AWAITING_PAYMENT = "AWAITING_PAYMENT",
  PARTIALLY_PAID = "PARTIALLY_PAID",
  COMPLETED = "COMPLETED",
  AWAITING_CONVERSION = "AWAITING_CONVERSION",
  CANCELLED = "CANCELLED",
  DEFAULTED = "DEFAULTED",
  REFUNDED = "REFUNDED",
}
