export enum PreferredSector {
  AI_ML = "AI/ML",
  FINTECH = "FinTech",
  HEALTHTECH = "HealthTech",
  EDTECH = "EdTech",
  AGRITECH = "AgriTech",
  ECOMMERCE = "E-commerce",
  SAAS = "SaaS",
  BLOCKCHAIN = "BlockChain/Crypto",
  GREENTECH = "GreenTech",
  PROPTECH = "Real Estate/PropTech",
  FOODTECH = "FoodTech",
  GAMING = "Gaming",
  SOCIAL_MEDIA = "Social Media",
  TRAVEL = "Travel & Hospitality",
  LOGISTICS = "Logistic & SupplyChain",
  CYBERSECURITY = "CyberSecurity",
  IOT = "IoT/Hardware",
  AR_VR = "AR/VR",
  SERVICES = "Services",
  OTHERS = "Others",
}
