export enum TransactionAction {
  CREDIT = "CREDIT",
  DEBIT = "DEBIT",
  TRANSFER = "TRANSFER",
}

export enum TransactionReason {
  SUBSCRIPTION = "SUBSCRIPTION",
  INVESTMENT = "INVESTMENT",
  PLATFORM_FEE = "PLATFORM_FEE",
  WITHDRAWAL = "WITHDRAWAL",
  REFUND = "REFUND",
}
